RegisterCommand("simpleui", function()
    SendNUIMessage({showmenu = true})
	SetNuiFocus(true, true)
end, false)

RegisterNUICallback('simpleui:nui:close', function(data, cb)
	SendNUIMessage({showmenu = false})
	SetNuiFocus(false, false)
    cb({})
end)
